### PR TITLE
fixed up pinnaclewrapper

### PR DESCRIPTION
**Pull request by harveysburger**
Hi, the library didn't really work anymore but now it should be ok. 

Changing from int to long was the first key change, but also some accounts have been shifted away from api.pinnacle.com to alternate urls. Your library still works fine with those other URLs except the versions for odds and fixtures api aren't the same depending on the domain  v3/odds , v1/odds  , etc... so I added some optional parameters (defaulted to the value you had before, "v1")

And... while in there I added period status and fixture parentId which are properties added about 1-2 years ago.

I also have a version locally that targets netstandard 2.0 so it can be consumed from netcore 2.2 or netframework 4.7.2 projects, I can push that in as well if you want.

### CODE REVIEW

**Comment by anderj017** [comment]
Nice work.

FYI I no longer use Pinnacle. Feel free to fork this and make your own library.

**Comment by harveysburger** [comment]
Cool thanks

Btw feel free to transfer to repo to me if you really don't care for it
anymore, or add me as contributor

Or I just evolve my own copy quietly :) up to you

Have a good day,

**Comment by anderj017** [comment]
I'll happily transfer it to you. Let me just figure out how to do it...

**Comment by anderj017** [comment]
I get an error saying: harveysburger/pinnaclewrapper already exists. Do you have a private repo? Wanna just temporarily rename it so I can transfer it to you?

**Comment by harveysburger** [comment]
Ok thanks

I renamed my fork https://github.com/harveysburger/pinnaclewrapperfork

Please try again
If you still get an error I'll delete my fork

**Comment by anderj017** [comment]
Still getting an error: harveysburger already has a repository in the anderj017/pinnaclewrapper network

**Comment by harveysburger** [comment]
Alright, thanks for your patience

I deleted my fork,

Hopefully will be ok now!

**Comment by anderj017** [comment]
Looks like it went through: Repository transfer to harveysburger requested

All the best!

**Comment by harveysburger** [comment]
Great, thanks

**Comment by harveysburger** [comment]
Hi,

I assume you didn't mind but I gave credits to you on the library which is
now published on nuget.org

Let me know if you rather not be listed or if you want something other than
"anderj017" to show up there :)


https://www.nuget.org/packages/PinnacleWrapper/2.0.0
<https://www.nuget.org/packages/PinnacleWrapper/2.0.0#>


[image: image.png]

**Pull request merged**
